<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'What3Words' => array($vendorDir . '/w3w-php-wrapper/src'),
);
