<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'What3words\\Geocoder\\' => array($vendorDir . '/what3words/w3w-php-wrapper/src'),
);
